### ISSUE TITLE
[Feature] [Enhancement]: Universe Homes Estate

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Dev#20]
### Notice

**If you are using WhiteCore-Sim please do not submit an issue report to Virtual Universe as we are unable to assist you.  Any issues reported to Virtual Universe which involve your use of WhiteCore-Sim will immediately be closed and you will be referred to WhiteCore-Sim.**

**In addition please do not submit issue reports regarding Virtual Universe to the WhiteCore-Sim issues tracker as they cannot help you and they will be immediately closed and you will be referred to Virtual Universe**

### Notice 2

**Effective August 1, 2016 - Any issues opened which do not have the provided questions answered will be closed immediately without further action.  The questions need to be answered to help provide us with as much information as possible to fix the bugs you find.  This has nothing to do with disliking reports or any individuals.  This has to do with getting to the root of the issues you report.  Thank you.**

### Issue Type

| Question      | Answer
| ------------- | ---------
| Bug?          | [no]
| New feature?  | [yes]

### For Feature requests please answer the following

**Describe the feature you are requesting**:

Establish the Universe Homes Estate

**Has the feature been implemented by a similar project**:

Yes Secondlife in fact does have the Linden Homes Estate for their premium homes

**What other project similar to Virtual Universe has implemented the feature**:

Opensim does not have the Opensim Homes regions as of yet but our upstream provider does have the ability to create the homes region (WhiteCore Homes).

**URL to where we can view the feature and or source code**:

### NOTE About Features

**The Second Galaxy Development Team will consider the features after we have seen enough interest by users of Virtual Universe.  The Feature must recieve at least five (5) core developers voting in favor of the feature for it to be included in a future release.**

### Steps to reproduce

1.
2.
3.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**Virtual Universe version:**

### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
@BruceStarfinder 

You were correct.  Diamond confirmed that the Premium Homes in Secondlife are in fact part of their own estate owned by Governor Linden.  She did say the estate number is in the 2900 range so it is not really clear yet whether this is a system estate or not.  So better to probably just make it a system estate.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
@EmperorStarfinder

This is what I had thought.  Given that the EstateID is above 100 then I
would initially say it probably isn't a system estate given our
understanding of how estates work in Virtual Universe (and in the upstream
provider WhiteCore).  However the mystery Linden Labs seems to always
unveil is their incredible habit of doing the reverse of the normal
understanding.  Thus I would say they probably do consider Linden Homes
Estate as a system estate based on it being run by the Lindens as a paid
for service (Linden Premium Homes).  So it would just be better for us to
make this a SystemEstate now so it is dealt with.  I would be curious as
to whether Diamond can provide us more info on what the region specifics
are on their premium home regions.  Upstream Provider seems to claim the
MaxPrims is 25,000.  The problem is if it is a full region on Secondlife
then it would in fact be MaxPrims = 15,000 same as the Full Regions
MaxPrims = 15,000  More Info Required.


-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
I will let @DiamondStarfinder or @KatilynnStarfinder if either are logged in to Secondlife right now.  One of the many things we do have right is we have a very well organized development team.  The whole purpose of our Administrative Support Services Work Group is to do research and provide the two development work groups with the information and administrative support we need to allow us to make our architectures much better.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by DiamondStarfinder** [comment]
Good morning,

To answer the questions here I am in Secondlife right now and will pass
the info about my Premium Home to you.

Region Name: Corbeau
Region Type: Linden Homes / Full Region
Rating: Mature
Estate Name: Linden Homes
Estate Owner: Governor Linden
Agent Limit: 55.00
Region Max Prims: 15,000 - This is based on the following:
     Max Agents                  55.00
     Allowed Prims Per lot:      117 x 55 = 6,435
     Total Prims used for Homes: 61  x 55 = 3,355
     Total Prims                     =      9,790
Experiences: 1 = The Mole Experience (not sure what this experience is)

I hope that helps a little bit.


Diamond Starfinder
Chief Administrative Officer
Work Group Leader
Administrative Support Services Work Group
Second Galaxy Development Team

**Comment by DiamondStarfinder** [comment]
I forgot to note that this is without the home being furnished.  These are
at their very basics.

Diamond Starfinder
Chief Administrative Officer
Work Group Leader
Administrative Support Services Work Group
Second Galaxy Development Team

**Comment by DiamondStarfinder** [comment]
I forgot one more thing:

Estate ID: 28996

Sorry about that


Diamond Starfinder
Chief Administrative Officer
Work Group Leader
Administrative Support Services Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
@DiamondStarfinder 

Thanks for the info.  I edited your initial comment with the items you forgot and deleted the additional comments to allow us to have it all in one place.  Hope you don't mind.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by DiamondStarfinder** [comment]
Not a problem.  Didn't know you could do that so I learn something new all
the time.


Diamond Starfinder
Chief Administrative Officer
Work Group Leader
Administrative Support Services Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Seeing the information @DiamondStarfinder has provided tells me a couple
of things.

First. The estate is an estate that is independent from the Mainland so we
need to create it.  Based on the EstateID she provided it would seem it
isn't a system estate but is intended to be but instead of making it a
system estate because it involves premium membership they took the easy
way out.  Therefore I think we probably should add it as a SystemEstate.

Second.  Based on her calculations, the assumption by the developers of
upstream provider WhiteCore is either incorrect or they are using a bigger
parcel size (bigger then 512 sqm) or some other assumption that is
incorrect.  Full regions in Secondlife only have a MaxPrims of 15,000 and
based on the fact that the Premium Home Regions are "Full Regions" they
have a max of 15,000 MaxPrims.  Looking at
WhiteCore.Modules.World.Startup.SimulationData.FileBasedSimulationData.cs
sets the full regions MaxPrims to 15000 by default.  Therefore in the same
file the comment assumes the Homes regions should have a default of
MaxPrims = 25000 is incorrect as this should also be MaxPrims = 15000.

Seeing as she notes that Governor Linden is the EstateOwner it makes sense
that this should really be one of the SystemEstates thus meaning there are
at least 3 SystemEstates.  The other key here is Linden Labs offers
Premium sandbox regions so I would be interested to know what Estate these
are in and how many prims are there to.

-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
It might be possible that WhiteCore's lead developer is trying to say the decorative stuff around the region that aren't directly associated with each parcel might cause the MaxPrims to exceed the 15,000 limit which is possible assuming the furniture they provide is not counted against the user's MaxPrims limit on the parcel.    That would be the only thing I can think of which would make some sense and the lead developer is just believing in the notion of being safe as opposed to sorry.  But I doubt very much the Lindens are just going to tell him this kind of information nor does he have a legitimate way of knowing this.  Linden Labs is out of date on many things so to make an architecture that is just like theirs is not really a wise idea seeing Linden Labs is heavily criticized for being bloated and out of date.  THe same way Opensim is.  

That said, seeing Opensimulator has already proven that the MaxPrims = 45000 for a full region can in fact be handled by most machines and the fact that on our proprietary architecture we increased that to MaxPrims = 100000, we should probably change those defaults a bit anyhow so I am not necessarily opposed to the Homes regions having a MaxPrims = 25000 by default though I believe this should be a configurable default anyhow.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Okay that rationale does make some sense.  If that assumption that they
did increase the MaxPrims to 25000 for that reason then it is correct. 
But my guess is they didn't really do that as it would in fact defy what
they constantly contend is the best MaxPrims for a full region.

So the question is do we want to set that at MaxPrims = 25000 or set a
different number?

-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
So here is what Linden Labs is claiming for their parcel sizes.  

Additional Land
(over 512 sqm) 	      Parcel Size        Prims per Parcel(approximate) 	        Monthly Land Use fee*
 
1/128 Region 	                512 sqm 	                117 	                                               US$5
1/64 Region 	             1,024 sqm 	                234 	                                               US$8
1/32 Region 	             2,048 sqm 	                468 	                                               US$15
1/16 Region 	             4,096 sqm 	                937 	                                               US$25
1/8 Region 	             8,192 sqm 	             1,875 	                                               US$40
1/4 Region 	           16,384 sqm 	             3,750 	                                               US$75
1/2 Region 	           32,768 sqm 	             7,500 	                                               US$125
Entire Region 	           65,536 sqm 	           15,000 	                                               US$195

Full Region 	           65,536 sqm 	           15,000 	                                               US$195
Homestead Region 	   65,536 sqm 	             3,750 	                                               US$125
Openspace Region 	   65,536 sqm 	                750 	                                               US$  75

Note: This information is taken from: http://secondlife.com/land/pricing.php

I am of course open to ideas on how to handle this issue.  I am not opposed to the Universe Homes regions being given a default MaxPrims = 25000 or a different number but whatever we do, I believe we need to keep it realistic with what we set the full regions MaxPrims to.  I am open to considering a change for the MaxPrims totals by default for each region type.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Okay in commit: 12d5147e8b2288b790a10ae929e17c25de7a497e I have added the
preliminary stuff for the new Universe Homes Estate.  Per our discussions
I decided its better to make it a SystemEstate as I am pretty confident
that LL would have done the same thing with theirs, but because it would
create them some problems they took the easy way out and probably
rightfully so.

There are a couple things I need to straighten out but for the moment it
does appear to have successfully created the estate.

I also added the default setting we use for Infinite Regions to the
Universe Homes regions as well.  I decided to leave the MaxPrims = 25000
until we decide how to proceed with this though I am inclined to believe
that this is wrong and its really MaxPrims = 15000.  But seeing that came
from the Upstream Provider WhiteCore-Sim and we have not ruled on this as
a team I have left it as is for the moment.

Once I correct the couple of things I accidentally caused with
establishing the HomesEstate as a SystemEstate I will hook up the Universe
Homes Regions to automatically join that estate upon creation.

-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Bruce,

I tested this and then checked the database.  Interestingly why its saying its creating successfully I am not sure but its likely the Primary Key error as the estate is not listed in the Estate settings table.  Ill test with the ISystemEstateService fix you just committed to.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Hey Emp,

Yes I think I have probably missed something relating to where I assign
the actual EstateIDs for SystemEstates which I am tracking down.  I did
get the same PRIMARY KEY error you did.  It is creating the estate but
assuming its really either the MainlandEstate or the SystemEstate which we
know it isn't but I suspect I am missing a piece to this which I need to
figure out.

But I thought you were on vacation so good to see your around.


-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Hey,

No we will be leaving for vacation on Friday afternoon.  I look forward to some camping (assuming it doesn't rain and the days are nice).

Its looking good I was going to point out your typo but you committed it before I could comment.  I take it you probably already know it still isn't adding the info to the mysql database (not sure if it is with sqlite).  perhaps thats part of the unreachable code warning you referenced.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Hey Emp,

I hope it doesn't rain on you to LOL!

Yes I did see the warning about the unreachable code.  I need to look into
that which I suspect that may be part of why its not adding the info to
the database.  There is probably something else here that I am missing as
well but I need to track it down.  It is odd though that the console
claims it successfully created the estate but yet hasn't added it to the
database.  Quite a very interesting mystery.  I'll keep plugging away at
it and figure it out though.  I got it this far I am not about to give up
on it.

-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Happy Friday!

Okay I think the reason it didn't the information to the database is
related to the Primary Key error both @EmperorStarfinder and I saw on the
consoles.  If this is correct then adding the (uint) should resolve this. 
@EmperorStarfinder if you can test this if you get this before you leave
for vacation and let me know, it would be good.  If so then this should
add the HomesEstate to the database in which case all thats left is making
sure the Homes Regions upon configuration are automatically added to the
Homes Estate.


-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Hey Bruce,

I am just getting final things caught up before we head out on vacation.  I tested the commit but essentially it didn't solve the problem.  It appears that the estate is trying to be committed but it defaults it back to Mainland Estate.  It is possible you might have missed a file somewhere in the Services directory.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Hey,

Okay that is interesting.  Another words it is assuming its a duplicate of
the mainland even though I have made sure it has its own estate id.  Guess
I need to do some more digging then to figure out why its not adding it as
its own estate.

If I don't have it done before you leave enjoy the vacation


-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by BruceStarfinder** [comment]
Per discussion with @EmperorStarfinder I am placing this feature
enhancement on hold in favor of the new SASE (System Account & System
Estate) service. which will provide support for the outer space version of
Estates (SolarSystems)

-- 
Bruce Starfinder
Core Developer
Grid Architecture Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Added to projects so closing

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
